### ISSUE TITLE
Doubt In README.md which converting void poniter to int straightly

### ISSUE THREAD

**Issue by AndroidInternal** [fuyufjh/GraphicBuffer#3]
like this

> readPtr = (void *)(int(readPtr) + stride * 4);

**Comment by fuyufjh** [comment]
Nope. This line increase readPtr `stride * 4` bytes

**Comment by AndroidInternal** [comment]
Sorry for trouble you and my poor explanation.

I mean I have concern on whether  the CPU Arch will impact the pointer' length or not by just converting the pointer straightly to int, such as armeabi-v7a and arm64-v8a.

In my program I used it in c program and just increase the void pointer stride * 4 bytes.

Thanks your example code very much.
