### ISSUE TITLE
Crash in destructor.

### ISSUE THREAD

**Issue by yihuang** [fuyufjh/GraphicBuffer#4]
I'm testing on samsung GT-I9158 device.
It crashes on destructor of GraphicBuffer: ``base->decRef(base);`` .
I'm using this with glEGLImageTargetTexture2DOES to upload texture.

**Comment by fuyufjh** [comment]
Sorry, I don't maintain this project anymore. PRs are always welcome if you solved it 😄

**Comment by yihuang** [comment]
According to this [stackover answer](http://stackoverflow.com/questions/21891235/android-crash-on-egldestroyimagekhr-using-graphicbuffer), which reference [mozillar's code](https://github.com/mozilla/gecko-dev/blob/86ab111afb36ef08fbbd265be93b37e7152d9bfe/widget/android/AndroidGraphicBuffer.cpp#L255).

I fixed the crash by:
1、Don't call ``eglDestroyImageKHR``.
2、Directly call the destructor when destruct GraphicBuffer.

```

GraphicBuffer::~GraphicBuffer()
{
    if (impl) {
        callDestructor<android::GraphicBuffer>(functions.destructor, impl);
        free(impl);
    }
}

```

EDIT: On my device, I don't need to remove ``eglDestroyImageKHR`` to fix the crash, but I guess it doesn't hurt either, since only thing it does is ``decRef`` the ``ANativeWindowBuffer``.

**Comment by OrenHg** [comment]
Have faced the same problem, Thanks a lot @yihuang 's answer. That works.
